apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../../manifests

namespace: sock-shop-prod

patches:
  - target:
      kind: Service
      name: front-end
    path: patches/front-end-svc-clusterip.yaml